"""Add folders and pinned chats

Revision ID: 1aaea73e6a0b
Revises: 
Create Date: 2026-02-21 10:12:43.561778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aaea73e6a0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_foreign_key(None, 'conversations', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'is_pinned')
    op.drop_column('conversations', 'folder_id')
    # ### end Alembic commands ###
