"""add custom agent fields

Revision ID: 4cbd52e84c29
Revises: 1aaea73e6a0b
Create Date: 2026-02-21 10:46:25.049844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cbd52e84c29'
down_revision: Union[str, None] = '1aaea73e6a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('agents', sa.Column('avatar_icon', sa.String(length=50), nullable=False, server_default=sa.text("'🤖'")))
    op.create_index(op.f('ix_agents_user_id'), 'agents', ['user_id'], unique=False)
    op.create_foreign_key(None, 'agents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_index(op.f('ix_agents_user_id'), table_name='agents')
    op.drop_column('agents', 'avatar_icon')
    op.drop_column('agents', 'is_public')
    op.drop_column('agents', 'user_id')
    # ### end Alembic commands ###
