"""admin overhaul foundation

Revision ID: 7daba0e431c1
Revises: 3c9137e7296c
Create Date: 2026-02-23 22:24:15.810181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7daba0e431c1'
down_revision: Union[str, None] = '3c9137e7296c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('model_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_suspended', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_suspended')
    op.drop_column('users', 'last_login')
    op.drop_column('messages', 'model_name')
    # ### end Alembic commands ###
