"""add_analytics_fields

Revision ID: c07f9a4cca43
Revises: bb2db7525d8e
Create Date: 2026-02-22 13:40:12.536672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c07f9a4cca43'
down_revision: Union[str, None] = 'bb2db7525d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('conversations', sa.Column('last_activity_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('messages', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('response_time_ms', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('used_rag', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('messages', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_agent_id'), 'messages', ['agent_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_foreign_key(None, 'messages', 'agents', ['agent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_agent_id'), table_name='messages')
    op.drop_column('messages', 'agent_id')
    op.drop_column('messages', 'used_rag')
    op.drop_column('messages', 'response_time_ms')
    op.drop_column('messages', 'tokens_used')
    op.drop_column('conversations', 'last_activity_at')
    op.drop_column('conversations', 'total_tokens')
    # ### end Alembic commands ###
