"""Add cascade delete for agent conversations

Revision ID: ef114dbaf9c7
Revises: 7daba0e431c1
Create Date: 2026-02-25 23:29:41.818855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef114dbaf9c7'
down_revision: Union[str, None] = '7daba0e431c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('conversations_agent_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_agent_id_fkey'), 'conversations', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###
